name: api testing

on: 
  schedule:
    # At 01:01 on every day-of-month" (see https://crontab.guru)
    - cron: '1 1 */1 * *'
  
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults
      
      - name: Run collection
        run: |
          newman run collection/cats-collection.postman_collection.json -e env/prod.postman_environment.json -r cli,htmlextra

      # Upload the contents of Test Results directory to workspace
      - name: Upload the Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: newman
        
