name: api testing

on: 
  schedule:
    # At every 1 hour" (see https://crontab.guru)
    - cron: '* */1 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Dependencies
        run: npm install --force

      - name: Run collection
        run: |
          newman run collection/cats-collection.postman_collection.json -e env/prod.postman_environment.json -r cli,htmlextra
